version: '2'
services:
    amitstore-app:
        image: amitstore
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://amitstore-postgresql:5432/amitstore
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    amitstore-postgresql:
        extends:
            file: postgresql.yml
            service: amitstore-postgresql
